In [3]:
import numpy as np

In [6]:
print(type(np.array([1,2,3,4])))

<class 'numpy.ndarray'>


In [17]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
a.ndim

2

In [12]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.float64)

In [13]:
a+b

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [15]:
a.T                    #or     a.transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])